dist:
  name: dev-otelcol
  description: Basic OTel Collector distribution for Developers
  output_path: ./dev-otelcol
  debug_compilation: true

    
exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/loggingexporter v0.73.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter
      v0.73.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.73.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.73.0
  - gomod: github.com/liatrio/otel-liatrio-contrib/receiver/ldapreceiver v0.1.0


replaces:
  - github.com/liatrio/otel-liatrio-contrib/receiver/ldapreceiver => /Users/adrielperkins/dev/observability/otel-liatrio-contrib/receiver/ldapreceiver/
      #- gomod:
      #    github.com/adrielp/otelreceivertest v0.1.0
