receivers:
  otlp:
    protocols:
      grpc:
  github:
    interval: 10s
        #ldap:
        #  interval: 10s
        #  search_filter: "(objectclass=*)"
        #  endpoint: "localhost"
        #  # TODO: use basic auth
        #  user: "cn=admin,dc=example,dc=org"
        #  pw: "admin"
        #  base_dn: "dc=example,dc=org"
        #  ignore_tls: true
     
processors:
  
exporters:
  logging:
    verbosity: detailed

  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp, github]
        #receivers: [otlp, ldap, github]
        #receivers: [ldapreceiver]
      processors: []
      exporters: [logging]
        #traces:
        #  receivers: [otlp]
        #  processors: []
        #  exporters: [jaeger, logging]
  telemetry:
    logs:
      level: debug
